---
title: "ApeGang Analysis"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libraries, message=TRUE, warning=FALSE}
library(tidyverse)
library(mongolite)
library(cowplot)
library("patchwork")
library(lubridate)

```


```{r}

url = "mongodb+srv://mvh:W1xIlKbF46rFCsiM@cluster0.ecrau.mongodb.net"

connection1 = mongo(
  collection = 'ape-gang-old_sales',
  db = "mvh",
  url = url,
  verbose = FALSE,
  options = ssl_options()
)

sales1 <- connection1$find()
```


```{r cars}
connection2 = mongo(
  collection = 'ape-gang_sales',
  db = "mvh",
  url =url,
  verbose = FALSE,
  options = ssl_options()
)

sales2 <- connection2$find()

ape_gang_sales <- rbind(sales1,sales2)
head(ape_gang_sales)

```

```{r}
AG_sum <- ape_gang_sales %>% 
  mutate(date = as_date(time)) %>% 
  group_by(date) %>% 
  summarise(date_mean = mean(sale_price),n_sales= n(),date_volume = sum(sale_price)) %>% 
  mutate(cum_volume = cumsum(date_volume))

tail(AG_sum)
```

```{r}
ggplot(data = AG_sum, aes(x = date, y = date_volume)) +
  geom_line(color = "#00AFBB", size = 1)+
  stat_smooth(color = "#FC4E07", fill = "#FC4E07",method = "loess",alpha=0.2)+
  labs(title = 'Ape Gang Sale Volume',x= 'Date', y='Average Volume (ETH)') +
  scale_x_date(date_labels = "%b/%Y")
```



```{r}

AG_logo <- png::readPNG("ape-gang.png",native = TRUE)
```


```{r}
ggplot(data = AG_sum, aes(x = date, y = date_mean)) +
  geom_line(color = "#00AFBB", size = 1)+
  stat_smooth(
  color = "#FC4E07", fill = "#FC4E07",
  method = "loess"
  )+
  labs(x= 'Date', y='Average price (ETH)') + 
  scale_x_date(date_labels = "%b/%Y")+   
  inset_element(p = AG_logo,
                left = 0.8,
                bottom = 0.01,
                right = 0.98,
                top = 0.25)
```


```{r}
AG_sum2 <- ape_gang_sales %>% 
  mutate(date = as_date(time)) %>% 
  group_by(date, collection) %>% 
  summarise(date_mean = mean(sale_price),n_sales= n(),date_volume = sum(sale_price)) %>% 
  group_by(collection) %>% 
  mutate(cum_volume = cumsum(date_volume))



p <- ggplot(data = AG_sum2, aes(x = date, y = cum_volume)) +
  geom_area(aes(fill=collection),color="black")+
  scale_x_date(date_labels = "%b/%Y")+
  ylab('Cumilative ApeGang Sales (ETH)')+      
  inset_element(p = AG_logo,
                left = 0.53,
                bottom = 0.1,
                right = 0.9,
                top = 0.8)
p      
```
```{r}
connection3 = mongo(
  collection = 'ape-gang_still_listed',
  db = "mvh",
  url =url,
  verbose = FALSE,
  options = ssl_options()
)
connection4 = mongo(
  collection = 'ape-gang-old_still_listed',
  db = "mvh",
  url =url,
  verbose = FALSE,
  options = ssl_options()
)

connection5 = mongo(
  collection = 'ape-gang-old_traits',
  db = "mvh",
  url =url,
  verbose = FALSE,
  options = ssl_options()
)

AG_listings <- rbind(connection3$find(), connection4$find())%>% 
  filter(listing_currency %in% c('ETH','WETH')) %>% 
  merge(connection5$find(),by='asset_id',all.x=T)
```


```{r}
floor_prices = data.frame()
for( x in c(0.5,0.75,1)){
  under_floor <- AG_listings %>% 
    filter(listing_price <x) %>% 
    count(collection) %>% 
    mutate(floor = x)
  floor_prices <- rbind(floor_prices,under_floor)
  #print(paste(nrow(under_floor),'listings under',x,'ETH'))
}
ggplot(floor_prices, aes(fill=collection, x=factor(floor),y=n, label=n))+
  geom_bar(position='stack',stat='identity')+ 
  scale_fill_manual(values = c("#00AFBB", "#E7B800"))+
  geom_text(position = "stack",vjust=1)+
  labs(x='ETH Floor',y='Number of Apes listed', fill='Opensea Collection')+
  geom_text(x=1.6, y=390, label='#DELISTYOURAPES',                  
           color="black", size=7 , angle=30, fontface="bold" )+
  theme(legend.position = 'bottom',
        panel.border = element_rect(linetype = "solid", fill = NA))+
  inset_element(p = AG_logo,
                left = 0.05,bottom = 0.6,right = 0.25,top = 0.95)

```


```{r}
source('R_functions.R')
sales_plot('boredapeyachtclub')+
  inset_element(p = png::readPNG("BAYC.png",native = TRUE),
                left = 0.05,
                bottom = 0.43,
                right = 0.3,
                top = 0.85)



```

```{r}
getwd()
```


